### ISSUE TITLE
Important persistent prefix coverage

### ISSUE THREAD

**Issue by csarven** [kjetilk/p5-rdf-ns-curated#1]
re: https://github.com/kjetilk/p5-rdf-ns-curated/blob/master/share/prefixes.csv I haven't looked closer, but if http://www.w3.org/2011/rdfa-context/rdfa-1.1 is not covered already, migt twant to include that by default.

**Comment by kjetilk** [comment]
Yeah, thanks! That was indeed the starting point! :-)
